interface = "wlp0s20f3"
long_uptime = false
long_shell = false
physical_cores = true
long_kernel = false

show = ["Host", "Kernel", "WindowManager", "Packages", "Terminal", "LocalIP", "Shell", "Uptime", "Terminal", "Memory", "Battery"]

theme = "Helium"

